// Generated by CoffeeScript 1.10.0
(function() {
  var Play,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Play = (function() {
    var key;

    key = 'play';

    function Play() {
      this.deleteAll = bind(this.deleteAll, this);
      this.iframe = bind(this.iframe, this);
      this.submit2 = bind(this.submit2, this);
      this.submit = bind(this.submit, this);
      var store;
      store = localStorage.getItem(key) || "[]";
      this.items = JSON.parse(store);
    }

    Play.prototype.submit = function() {
      var store;
      if (this.message == null) {
        return;
      }
      this.items.push(this.message);
      store = JSON.stringify(this.items);
      localStorage.setItem(key, store);
      return this.message = "";
    };

    Play.prototype.submit2 = function() {
      var store;
      if (this.message2 == null) {
        return;
      }
      this.items.push(this.message2);
      store = JSON.stringify(this.items);
      localStorage.setItem(key, store);
      return this.message2 = "";
    };

    Play.prototype.iframe = function() {
      var frame;
      frame = document.createElement('iframe');
      frame.src = "iframe2.html";
      return document.body.appendChild(frame);
    };

    Play.prototype.deleteAll = function() {
      this.items = [];
      return localStorage.removeItem(key);
    };

    return Play;

  })();

  window.onload = function() {
    var el;
    window.app = new Play();
    el = document.getElementById('content');
    return rivets.bind(el, app);
  };

}).call(this);
