// Generated by CoffeeScript 1.8.0
(function() {
  var Play,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Play = (function() {
    var key;

    key = 'play';

    function Play() {
      this.deleteAll = __bind(this.deleteAll, this);
      this.submit = __bind(this.submit, this);
      var store;
      store = localStorage.getItem(key) || "[]";
      this.items = JSON.parse(store);
    }

    Play.prototype.submit = function() {
      var store;
      if (this.message == null) {
        return;
      }
      this.items.push(this.message);
      store = JSON.stringify(this.items);
      localStorage.setItem(key, store);
      return this.message = "";
    };

    Play.prototype.deleteAll = function() {
      this.items = [];
      return localStorage.removeItem(key);
    };

    return Play;

  })();

  window.onload = function() {
    var el;
    window.app = new Play();
    el = document.getElementById('content');
    return rivets.bind(el, app);
  };

}).call(this);
