// Generated by CoffeeScript 1.8.0
(function() {
  var Article;

  Article = (function() {
    function Article() {
      this.error = null;
      this.note = null;
      this.initialize();
    }

    Article.prototype.filename = null;

    Article.prototype.initialize = function() {};

    Article.prototype.onBind = function() {};

    return Article;

  })();

}).call(this);
