// Generated by CoffeeScript 1.8.0
(function() {
  var Config;

  Config = (function() {
    function Config(opts) {
      var prop, result, _i, _len;
      result = {
        defaultBits: 2048,
        keyringTag: 'keyring'
      };
      for (_i = 0, _len = opts.length; _i < _len; _i++) {
        prop = opts[_i];
        if (opts.hasOwnPropety(prop)) {
          result[prop] = opts[prop];
        }
      }
      return result;
    }

    return Config;

  })();

  window.Config = Config;

}).call(this);
