// Generated by CoffeeScript 1.8.0
(function() {
  var Config;

  Config = (function() {
    function Config(opts) {
      var prop, result;
      if (opts == null) {
        opts = {};
      }
      result = {
        keyName: 'privateKey',
        defaultBits: 2048
      };
      for (prop in opts) {
        if (opts.hasOwnPropety(prop)) {
          result[prop] = opts[prop];
        }
      }
      return result;
    }

    return Config;

  })();

  window.Config = Config;

}).call(this);
