// Generated by CoffeeScript 1.8.0
(function() {
  var Keyring;

  Keyring = (function() {
    var keyring;

    keyring = [];

    function Keyring(config) {
      this.config = config;
      this.load();
    }

    Keyring.prototype.purge = function() {
      keyring = [];
      return localStorage.removeItem(this.config.keyringTag);
    };

    Keyring.prototype.load = function() {
      var e, json;
      json = localStorage.getItem(this.config.keyringTag);
      keyring = [];
      if (json) {
        try {
          return keyring = JSON.parse(json);
        } catch (_error) {
          e = _error;
          throw "Unable to parse the 'keys' storage";
        }
      }
    };

    Keyring.prototype.save = function() {
      var json;
      json = JSON.stringify(keyring);
      return localStorage.setItem(this.config.keyringTag, json);
    };

    Keyring.prototype.find = function(email) {
      var key, _i, _len;
      for (_i = 0, _len = keyring.length; _i < _len; _i++) {
        key = keyring[_i];
        if (key.email === email) {
          return key;
        }
      }
    };

    Keyring.prototype.add = function(key) {
      keyring.push(key);
      return this.save();
    };

    Keyring.prototype.length = function() {
      return keyring.length;
    };

    Keyring.prototype.at = function(idx) {
      return keyring[idx];
    };

    Keyring.prototype.all = function() {
      return keyring;
    };

    return Keyring;

  })();

  window.Keyring = Keyring;

}).call(this);
