// Generated by CoffeeScript 1.8.0
(function() {
  window.app.controller('CreateKeysController', [
    '$scope', 'config', 'keyring', function($scope, config, keyring) {
      $scope.form = {
        bits: config.defaultBits,
        name: null,
        email: null,
        passphrase: null,
        confirm: null
      };
      $scope.error = null;
      $scope.spinner = null;
      $scope.keypair = null;
      return $scope.generateKeys = function() {
        var options;
        $scope.error = null;
        if (!$scope.newKeysForm.$valid) {
          $scope.error = "Form error. Please see below for more information.";
          return;
        }
        if ($scope.form.passphrase !== $scope.form.confirm) {
          $scope.error = "The passphrase and the passphrase confirmation do not match";
          return;
        }
        if (keyring.findByIdOrEmail($scope.form.email, $scope.form.name)) {
          $scope.error = "A key with this name or email already exists";
          return;
        }
        $scope.spinner = true;
        options = {
          numBits: $scope.form.bits,
          userId: "" + $scope.form.name + " <" + $scope.form.email + ">",
          passphrase: $scope.form.passphrase
        };
        return openpgp.generateKeyPair(options).then(function(keypair) {
          return $scope.$apply(function() {
            $scope.spinner = false;
            $scope.keypair = keypair;
            return storage.saveOwnKey(keypair);
          });
        })["catch"](function(error) {
          return console.log(error);
        });
      };
    }
  ]);

}).call(this);
