// Generated by CoffeeScript 1.8.0
(function() {
  window.app.controller('ListKeysController', [
    '$scope', 'config', 'storage', function($scope, config, storage) {
      return $scope.selectedKey = function() {
        return storage.ownKeys;
      };
    }
  ]);

}).call(this);
