// Generated by CoffeeScript 1.8.0
(function() {
  window.app.controller('MainController', [
    '$scope', 'config', function($scope, config) {
      return $scope.createKeys = false;
    }
  ]);

}).call(this);
