// Generated by CoffeeScript 1.8.0
(function() {
  chrome.runtime.onMessage.addListener(function(msg, sender, sendResponse) {
    if (msg.loadModules) {
      chrome.tabs.executeScript(null, {
        file: "bower_components/openpgp/dist/openpgp.min.js"
      }, function() {
        return sendResponse("Got the message");
      });
    }
    return true;
  });

}).call(this);
