// Generated by CoffeeScript 1.8.0
(function() {
  var openpgp;

  openpgp = "bower_components/openpgp/dist/openpgp.min.js";

  chrome.runtime.onMessage.addListener(function(msg, sender, sendResponse) {
    if (msg.loadOpenPgp) {
      chrome.tabs.executeScript(null, {
        file: openpgp
      }, function() {
        return sendResponse("Got the message");
      });
    }
    return true;
  });

}).call(this);
