// Generated by CoffeeScript 1.8.0
(function() {
  var config, key, keyring;

  config = new window.Config({
    keyringTag: 'keyring_test'
  });

  keyring = key = null;

  describe("A key", function() {
    beforeAll(function() {
      return key = new window.Key(config);
    });
    it("can be created", function(done) {
      return key.create("tester", "tester@example.com", "alabama123").then(function() {
        expect(key.publicKeyArmored).toBeDefined();
        expect(key.privateKeyArmored).toBeDefined();
        return done();
      });
    });
    it("has a title", function() {
      return expect(key.title).toBeDefined();
    });
    return it("turns into JSON", function() {
      return expect(key.toJSON().id).toBe("tester");
    });
  });

  describe("A keyring", function() {
    beforeAll(function() {
      keyring = new window.KeyRing(config);
      return keyring.purge();
    });
    it("is empty in the begining", function() {
      return expect(keyring.length()).toBe(0);
    });
    it("can add keys", function() {
      keyring.add(key);
      return expect(keyring.length()).toBe(1);
    });
    it("can save", function() {
      keyring.save();
      return expect(localStorage.getItem(config.keyringTag)).toBeDefined();
    });
    return it("can load", function() {
      var kr;
      kr = new window.KeyRing(config);
      expect(kr.length()).toBe(1);
      return expect(kr.at(0).toJSON().id).toBe(key.toJSON().id);
    });
  });

}).call(this);
