// Generated by CoffeeScript 1.8.0
(function() {
  var app, bodyParser, express, port, storage;

  express = require('express');

  bodyParser = require('body-parser');

  port = 5000;

  storage = [];

  app = express();

  app.use(bodyParser.json());

  app.get('/x/:id', function(req, res) {
    var id;
    id = req.params.id;
    return res.json(storage[id]);
  });

  app.post('/x', function(req, res) {
    var payload;
    payload = req.body;
    if (!payload) {
      res.statusCode = 400;
      res.json({
        error: "Payload missing"
      });
      return;
    }
    storage.push(payload);
    return res.json({
      id: storage.length
    });
  });

  app.listen(port, function() {
    return console.log("Server listening on port " + port + " ...");
  });

}).call(this);
