// Generated by CoffeeScript 1.8.0
(function() {
  var Storage, data;

  data = {};

  Storage = (function() {
    function Storage() {}

    Storage.prototype.set = function(key, value, callback) {
      data[key] = value;
      return callback();
    };

    Storage.prototype.get = function(key, callback) {
      return callback(data[key]);
    };

    Storage.prototype.remove = function(key, callback) {
      delete data[key];
      return callback();
    };

    return Storage;

  })();

  module.exports = Storage;

}).call(this);
